# Default values for code.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.local/code-server
  pullPolicy: Always
  tag: "node23"

fullnameOverride: "code-a80214d6-5deb-4b5e-9ddb-0cdcbaee91ec"

resources: 
  limits:
    cpu: 2000m
    memory: 8192Mi
  requests:
    cpu: 2000m
    memory: 8192Mi

service:
  type: ClusterIP
  port: 8443

volumes: 
- name: workspace
  persistentVolumeClaim:
    claimName: code-a80214d6-5deb-4b5e-9ddb-0cdcbaee91ec

# Additional volumeMounts on the output Deployment definition.
volumeMounts: 
- name: workspace
  mountPath: "/config/workspace"
  readOnly: false
